<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoaiPhongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('loai_phongs')->delete();
        DB::table('loai_phongs')->insert([
            ['id' => '1', 'ten_loai_phong' => 'Phòng Standard', 'dien_tich' => '20', 'so_giuong' => '1', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://pix8.agoda.net/hotelImages/55705262/-1/d33f7266396a6f48fd5618686a69890b.jpg?ce=0&s=1024x', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-door-open me-2"></i> Có các phòng thông nhau</p><p><i class="fa-solid fa-phone-volume me-2"></i> Điện thoại</p><p><i class="fa-solid fa-shirt me-2"></i> Áo choàng tắm</p><p><i class="fa-solid fa-soap me-2"></i> Vật dụng tắm rửa</p><p><i class="fa-solid fa-spray-can-sparkles me-2"></i> Nước hoa</p><p><i class="fa-solid fa-snowflake me-2"></i> Điều hoà</p>'],
            ['id' => '2', 'ten_loai_phong' => 'Phòng Superior', 'dien_tich' => '25', 'so_giuong' => '2', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/556907343.jpg?k=70999b4df5dde7bd1fa5cee88b4edcdef2477a3039e1d129f18bb569028ed7b8&o=&s=1024x', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-shoe-prints me-2"></i> Dép đi trong nhà</p><p><i class="fa-solid fa-bottle-water me-2"></i> Nước uống</p><p><i class="fa-solid fa-martini-glass-citrus me-2"></i> Tủ lạnh nhỏ trong phòng</p><p><i class="fa-solid fa-wifi me-2"></i> Wifi</p><p><i class="fa-solid fa-clock me-2"></i> Đồng hồ báo thức</p><p><i class="fa-solid fa-rug me-2"></i> Thảm</p><p><i class="fa-solid fa-volume-xmark me-2"></i> Cách âm</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p>'],
            ['id' => '3', 'ten_loai_phong' => 'Phòng Deluxe', 'dien_tich' => '15', 'so_giuong' => '2', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/552982086.jpg?k=baf394d5776d2b8f8b4219877bbaaccc7f629aac51e604dd5b3bd043b222c915&o=&s=1024x', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>'],
            ['id' => '4', 'ten_loai_phong' => 'Phòng Suite', 'dien_tich' => '30', 'so_giuong' => '1', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://pix8.agoda.net/hotelImages/23168138/328908056/bcbc05be111ee21b734332b297089ccb.jpg?ca=18&ce=1&s=1024x', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>'],
            ['id' => '5', 'ten_loai_phong' => 'Phòng View Biển', 'dien_tich' => '20', 'so_giuong' => '1', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/427680042.jpg?k=f490b8cd6dd944d024f2edf79d3a391225955ec635fb48070a01701cf8cb6244&o=&s=1024x', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-couch me-2"></i> Sofa</p><p><i class="fa-solid fa-trash me-2"></i> Thùng rác</p><p><i class="fa-solid fa-kitchen-set me-2"></i> Nhà bếp</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà tắm dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Nhà vệ sinh dành cho người khuyết tật</p><p><i class="fa-regular fa-circle-check me-2"></i> Đồ dùng cho giấc ngủ thoải mái</p>'],
            ['id' => '6', 'ten_loai_phong' => 'Phòng VIP', 'dien_tich' => '22', 'so_giuong' => '1', 'so_nguoi_lon' => rand(1, 5), 'so_tre_em' => rand(1, 4), 'tinh_trang' => '1', 'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl6cJhgsnx6MXM7B3nFmNIGyy0RqrbxIh4CQ&s', 'tien_ich' => '<p><i class="fa-solid fa-ban-smoking fa-xl me-2"></i> Không hút thuốc</p><p><i class="fa-solid fa-shower fa-xl me-2"></i> Vòi sen</p><p><i class="fa-solid fa-soap me-2"></i> Vật dụng tắm rửa</p><p><i class="fa-solid fa-spray-can-sparkles me-2"></i> Nước hoa</p><p><i class="fa-solid fa-snowflake me-2"></i> Điều hoà</p><p><i class="fa-solid fa-shoe-prints me-2"></i> Dép đi trong nhà</p><p><i class="fa-solid fa-bottle-water me-2"></i> Nước uống</p><p><i class="fa-solid fa-martini-glass-citrus me-2"></i> Tủ lạnh nhỏ trong phòng</p><p><i class="fa-solid fa-wifi me-2"></i> Wifi</p><p><i class="fa-solid fa-clock me-2"></i> Đồng hồ báo thức</p>'],
        ]);
    }
}
